import { createFileRoute, Link } from "@tanstack/react-router";
import { FileText, Play, Download, Terminal, Layers, BarChart3 } from "lucide-react";
import { FeaturePageShell } from "@/components/landing/FeaturePageShell";

export const Route = createFileRoute("/features/scripts")({
  component: ScriptsPage,
});

const STEPS = [
  {
    num: "01",
    tag: "Prerequisite",
    title: "Approve your test cases",
    body: "Script generation works on approved test cases only. Each case with status 'Approved' in a suite is eligible. Draft and Ready cases are skipped.",
    note: "→ Status: Draft → Ready → Approved",
  },
  {
    num: "02",
    tag: "MCP server",
    title: "Install the local runner",
    body: "The Playwright scripts run through a local MCP server on port 3100. Setup takes about five minutes on Mac or Windows — the page walks you through it step by step.",
    note: "→ Mac and Windows guides included",
  },
  {
    num: "03",
    tag: "Generation",
    title: "Generate .spec.ts files",
    body: "QAMind groups test cases that share the same preconditions into a single merged spec file. The AI converts each case's steps and expected results into Playwright assertions.",
    note: "→ One .spec.ts per logical group, not per case",
  },
  {
    num: "04",
    tag: "Run",
    title: "Execute or download",
    body: "Trigger the run directly from QAMind — results come back as a pass/fail log per test case. Or download the .spec.ts files and drop them into your existing CI setup.",
    note: "→ Results tracked in Run History",
  },
];

const FACTS = [
  { label: "Framework", value: "Playwright — TypeScript (.spec.ts)" },
  { label: "Runner port", value: "MCP server on localhost:3100" },
  { label: "Grouping logic", value: "Cases with shared preconditions merge into one spec file" },
  { label: "Input required", value: "Test cases in 'Approved' status only" },
  { label: "Platforms", value: "Mac and Windows (Linux: manual setup)" },
  { label: "Export", value: "Download .spec.ts files for use in any CI pipeline" },
];

const RELATED = [
  {
    icon: <Play size={15} strokeWidth={1.75} />,
    name: "Run History",
    desc: "Every run tracked with per-case pass/fail/skip. Full error detail on failures.",
    href: "/features/runs",
  },
  {
    icon: <Layers size={15} strokeWidth={1.75} />,
    name: "Test Suites",
    desc: "Organise cases into suites. Approve before generating scripts.",
    href: "/features/suites",
  },
  {
    icon: <BarChart3 size={15} strokeWidth={1.75} />,
    name: "Analytics",
    desc: "Pass rate trends, flaky test flags, and coverage gaps — all from run results.",
    href: "/features/analytics",
  },
];

function MockScript() {
  return (
    <div className="feat-mock-window">
      <div className="feat-mock-chrome">
        <div className="feat-mock-dots">
          <span className="feat-mock-dot feat-mock-dot-r" />
          <span className="feat-mock-dot feat-mock-dot-y" />
          <span className="feat-mock-dot feat-mock-dot-g" />
        </div>
        <span className="feat-mock-path">qamind.ai / generate-scripts</span>
        <span className="feat-mock-badge-tag">PLAYWRIGHT</span>
      </div>
      <div className="feat-mock-body">
        <p className="feat-mock-label-sm mb-2">Generated spec — password-reset.spec.ts</p>
        <div style={{ background: "#0f0d0b", border: "1px solid #2e2520", borderRadius: 6, padding: "0.75rem", fontFamily: "var(--font-mono)", fontSize: 10, color: "#7d9e8c", lineHeight: 1.65 }}>
          <div style={{ color: "#5a4e44" }}>{"// Auto-generated by QAMind · Suite: Auth"}</div>
          <div style={{ color: "#9b8b7a" }}>{"import"} <span style={{ color: "#c2553e" }}>{"{ test, expect }"}</span> <span style={{ color: "#9b8b7a" }}>{"from '@playwright/test';"}</span></div>
          <br />
          <div><span style={{ color: "#c2553e" }}>{"test"}</span><span style={{ color: "#9b8b7a" }}>{"('TC-041 valid reset — password updated', async ("}</span><span style={{ color: "#7d9e8c" }}>{"{ page }"}</span><span style={{ color: "#9b8b7a" }}>{")"}</span> {"=> {"}</div>
          <div style={{ paddingLeft: "1rem", color: "#7d9e8c" }}>{"await page.goto('/forgot-password');"}</div>
          <div style={{ paddingLeft: "1rem", color: "#7d9e8c" }}>{"await page.fill('#email', 'user@example.com');"}</div>
          <div style={{ paddingLeft: "1rem", color: "#7d9e8c" }}>{"await page.click('#submit');"}</div>
          <div style={{ paddingLeft: "1rem" }}><span style={{ color: "#d9744a" }}>{"await expect"}</span><span style={{ color: "#9b8b7a" }}>{"(page.locator('.success-msg')).toBeVisible();"}</span></div>
          <div>{"});"}</div>
        </div>
        <div className="flex items-center gap-2 mt-3">
          <button className="feat-mock-btn-primary-sm"><Play size={10} /> Run suite</button>
          <button style={{ display: "inline-flex", alignItems: "center", gap: 4, padding: "0.3rem 0.65rem", border: "1px solid #2e2520", borderRadius: 5, fontFamily: "var(--font-mono)", fontSize: 10, color: "#9b8b7a", background: "transparent", cursor: "default" }}><Download size={10} /> Download .spec.ts</button>
        </div>
      </div>
    </div>
  );
}

function ScriptsPage() {
  return (
    <FeaturePageShell
      title="Playwright Script Generator"
      description="Generate runnable Playwright .spec.ts files from approved test cases via QAMind's local MCP server. Run them inside QAMind or drop them into your CI pipeline."
    >
      <section data-section-theme="dark">
        <div className="feat-hero">
          <p className="feat-eyebrow fade-up">
            <span style={{ color: "var(--c-accent)" }}>&sect;</span> PLAYWRIGHT SCRIPT GENERATOR
          </p>
          <h1 className="feat-headline fade-up fade-up-d1">
            Approved cases<br />become runnable tests.
          </h1>
          <p className="feat-subtext fade-up fade-up-d2">
            Once your test cases are approved, QAMind generates Playwright <code className="font-mono text-[0.9em]">.spec.ts</code> files — one file per logical group. Run them from inside QAMind or take the files and run them anywhere.
          </p>
          <div className="feat-hero-chips fade-up fade-up-d3">
            <span className="feat-chip"><span className="feat-chip-dot" />Playwright TypeScript</span>
            <span className="feat-chip"><span className="feat-chip-dot" />Local MCP server</span>
            <span className="feat-chip"><span className="feat-chip-dot" />Downloadable .spec.ts</span>
            <span className="feat-chip"><span className="feat-chip-dot" />Mac + Windows</span>
          </div>
          <div className="flex flex-wrap gap-3 fade-up fade-up-d4">
            <Link to="/auth" search={{ mode: "signup" }} className="fn-nav-action is-primary">Get started</Link>
            <Link to="/features/generate" className="fn-nav-action">Generate test cases first →</Link>
          </div>
        </div>
      </section>

      <section data-section-theme="dark">
        <div className="mx-auto max-w-5xl px-6 pb-16">
          <div className="fade-up"><MockScript /></div>
        </div>
      </section>

      <section data-section-theme="light">
        <div className="feat-steps-section">
          <div className="feat-steps-inner">
            <div className="feat-steps-header fade-up">
              <p className="feat-eyebrow"><span style={{ color: "var(--c-accent)" }}>&sect;</span> HOW IT WORKS</p>
              <h2 className="font-display text-[clamp(1.75rem,3.5vw,2.4rem)] font-semibold tracking-[-0.02em] text-[var(--c-text)] mt-2 max-w-[500px]">
                Cases in. Scripts out. Results tracked.
              </h2>
            </div>
            <div className="feat-steps-grid">
              {STEPS.map((step, i) => (
                <div key={step.num} className={`feat-step fade-up fade-up-d${i + 1}`}>
                  <span className="feat-step-num">{step.num}</span>
                  <div>
                    <p className="feat-step-tag">{step.tag}</p>
                    <h3 className="feat-step-title">{step.title}</h3>
                    <p className="feat-step-body">{step.body}</p>
                    <p className="feat-step-note">{step.note}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section data-section-theme="light">
        <div className="mx-auto max-w-3xl px-6 pb-20">
          <p className="feat-eyebrow mb-4 fade-up"><span style={{ color: "var(--c-accent)" }}>&sect;</span> TECHNICAL DETAILS</p>
          <div className="feat-fact-box fade-up fade-up-d1">
            <div className="feat-fact-heading">Script generator specs</div>
            {FACTS.map((f) => (
              <div key={f.label} className="feat-fact-row">
                <span className="feat-fact-label">{f.label}</span>
                <span className="feat-fact-value">{f.value}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section data-section-theme="dark">
        <div className="mx-auto max-w-5xl px-6 py-16">
          <p className="feat-eyebrow mb-6 fade-up"><span style={{ color: "var(--c-accent)" }}>&sect;</span> SETUP WALKTHROUGH</p>
          <div className="feat-demo-placeholder fade-up fade-up-d1">
            <div className="feat-demo-icon"><Terminal size={22} /></div>
            <p className="feat-demo-label">Video — runner setup</p>
            <p className="feat-demo-title">Install and connect the local runner</p>
            <p className="feat-demo-sub">
              Watch the full setup on Mac or Windows: install the MCP server, connect it to QAMind, generate your first script, and run it — under 8 minutes.
            </p>
            <span style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--c-text-dim)", border: "1px solid var(--c-border)", borderRadius: 6, padding: "0.25rem 0.6rem", position: "relative", zIndex: 1 }}>Coming soon</span>
          </div>
        </div>
      </section>

      <section data-section-theme="dark">
        <div className="mx-auto max-w-5xl px-6 pb-20">
          <p className="feat-eyebrow mb-4 fade-up"><span style={{ color: "var(--c-accent)" }}>&sect;</span> RELATED</p>
          <div className="feat-related-grid">
            {RELATED.map((r, i) => (
              <Link key={r.href} to={r.href as any} className={`feat-related-card fade-up fade-up-d${i + 1}`}>
                <div className="feat-related-icon">{r.icon}</div>
                <p className="feat-related-name">{r.name}</p>
                <p className="feat-related-desc">{r.desc}</p>
                <span className="feat-related-arrow">→</span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section data-section-theme="light">
        <div className="feat-cta-section fade-up">
          <p className="feat-eyebrow justify-center"><span style={{ color: "var(--c-accent)" }}>&sect;</span> GET STARTED</p>
          <h2 className="feat-cta-headline">Ready to run your first Playwright suite?</h2>
          <p className="feat-cta-sub">Sign up, generate test cases, approve them, and generate scripts. The setup guide walks you through the local runner in under ten minutes.</p>
          <div className="feat-cta-actions">
            <Link to="/auth" search={{ mode: "signup" }} className="fn-nav-action is-primary">Start free</Link>
            <Link to="/features/generate" className="fn-nav-action">Generate cases first →</Link>
          </div>
        </div>
      </section>
    </FeaturePageShell>
  );
}
